### ISSUE TITLE
Azure Deploy

### ISSUE THREAD

**Issue by Romoku** [Romoku/voat#1]
Rethink the overall story for deploying to Azure.

* ~~How to handle Azure config~~
* ~~FAKE~~
* ~~Appveyor~~
* ~~Database setup~~

**Comment by Romoku** [comment]
Azure config and FAKE resolved with 52554bd

**Comment by Romoku** [comment]
FAKE is able to Build the app, run Unit Tests, and deploy to Azure.

The `UnitTest` task will need to be tweaked once Unit Testing conventions are made to pickup xUnit tests.

Current only Azure Websites are supported as a deploy target. This is accomplished with MSBuild `DeployOnBuild` target. MSBuild needs an `Azure.pubxml` located under `whoaverse\Properties\PublishProfiles`.

You can generate one using Visual Studio. I will include a sample in the repo base.

Additionally you will need a PublishSettings for the Azure Website. Under your Azure Website there is a Dashboard tab. Click on the "Download the publish profile" link and save it as `Azure.PublishSettings` under `whoaverse\Properties\PublishProfiles`.

**Comment by Romoku** [comment]
AppVeyor resolved with 52554bd

**Comment by Romoku** [comment]
The `Web.config` files are automatically generated on first build with `build.cmd`. This will simplify people getting started.

Additionally the `./Whoaverse/Web.config ` is automatically transformed based on current configuration (Debug/Azure/Release) when the user hits F5. This works by taking the transform (Debug/Azure/Release) and transforming `Web.Base.Config` then writing the output to `Web.config`.

I have purchased the $30 open source pro plan on AppVeyor since the builds were terribly slow otherwise. I need to open a discussion on the part Voat/Voat about Continuous Integration and Continuous Delivery.

**Comment by TNTGav** [comment]
As a relative newbie to github can you explain what exactly this does and how to use it. It sounds like it will make building the application from scratch a lot easier.

I also think it would be worth looking into inserting content as part of that build process if anyone else thinks that is a good idea. It makes things easier to test.

**Comment by Romoku** [comment]
So the first thing you will need is [Visual Studio 2013 Community Edition](https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx) or higher.

Visual Studio comes with F#, so if you are on Windows you are all set. Additionally you will need to install [Putty](http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html) and [msysgit](https://msysgit.github.io/). There are plenty of tutorials on configuration git but the cliff notes are:

* Choose add git to path
* Check `commit as is; checkout as is`
* Check use Putty for ssh
* Follow the [Github guide](https://help.github.com/articles/setting-your-username-in-git/) for identity

After you have installed VS and related tools you can begin building Voat.

Clone the Voat repository from here. Checkout the develop branch.

    git clone https://github.com/Romoku/voat
    git checkout develop

Now change into the `Whoaverse` directory and run `build.cmd`

    cd Whoaverse
    build.cmd

This should bootstrap your new Voat installation, build Voat, and run the unit tests. After that you can open up `Voat.sln` inside Visual Studio.

**Comment by Romoku** [comment]
The next thing you need is [SQL Server 2014 Express with Advanced Services](https://www.microsoft.com/en-us/download/confirmation.aspx?id=42299). This will include SQL Server Management Studio which you need to setup the database until I finish my next task.

Install SQL Server is relatively straightforward. After it is installed then open SQL Server Management Studio.

In the `Server Name` put `<PC-NAME>\.SQLEXPRESS` where the `<PC-NAME>` is in the System dialog.

It should use windows authentication with your user account if you setup SQL Server right.

Once it is open there is an `Object Explorer`. You want to right click the database at the top level of folder tree and go to properties.

This opens up the 'Server Properties' dialog. Under the 'Select a page' click 'Security' then click the 'SQL Account and Windows Authentication Mode' if it is not already selected.

Now click 'OK'. Right click the database again and click 'Restart '.

Now that mixed authentication is enabled we can create the databases.

On the taskbar there is a button next to 'Save All' called 'New Query'. Click on 'New Query' and it will open a new inner window.

Copy and paste:

    CREATE DATABASE voat;
    GO

    CREATE DATABASE voatUsers;
    GO

    USE voat;
    GO

    CREATE LOGIN voat WITH PASSWORD = 'secretpwd'
    GO

    IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'voat')
    BEGIN
        CREATE USER voat FOR LOGIN voat
        EXEC sp_addrolemember N'db_owner', N'voat'
    END;
    GO

    USE voatUsers;
    GO

    CREATE LOGIN voat_users WITH PASSWORD = 'secretpwd'
    GO

    IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'voatusers')
    BEGIN
        CREATE USER voatusers FOR LOGIN voatusers
        EXEC sp_addrolemember N'db_owner', N'voatusers'
    END;
    GO

This script will create the databases.

Now look for a file inside the Voat solution of Visual Studio called `Web.Base.config`.

Open this and it should look like:

    <?xml version="1.0"?>
    <configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
      <connectionStrings>
        <add name="whoaverseUsers"
            connectionString="Server=.\SQLExpress, 1433;Initial Catalog=voatUsers;Persist Security Info=True;User ID=whoaverse_users;Password=secretpwd"
            xdt:Transform="SetAttributes" xdt:Locator="Match(name)"/>
        <add name="whoaverseEntities"
            connectionString="metadata=res://*/Models.WhoaverseEntityDataModel.csdl|res://*/Models.WhoaverseEntityDataModel.ssdl|res://*/Models.WhoaverseEntityDataModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;server=.\SQLExpress;initial catalog=voat;persist security info=True;user id=whoaverse;password=secretpwd;MultipleActiveResultSets=True;App=EntityFramework&quot;"
            xdt:Transform="SetAttributes" xdt:Locator="Match(name)"/>
      </connectionStrings>
      <appSettings>
        <add key="recaptchaPublicKey"
             value=""
             xdt:Transform="SetAttributes" xdt:Locator="Match(key)" />
        <add key="recaptchaPrivateKey"
             value=""
             xdt:Transform="SetAttributes" xdt:Locator="Match(key)" />
      </appSettings>
    </configuration>

Under the `connectionString` are two XML elements that contain `whoaverseUsers` and `whoaverseEntities`. Replace the relevant portions `User Id`, `Password` with what we made up there.

**Comment by Romoku** [comment]
The final piece you need is a Recaptcha code. Go to the [website](https://www.google.com/recaptcha/intro/index.html) and click 'Get reCAPTCHA'. Then under 'Register a new site' enter: 'Local Voat' for the label, 'localhost' under the domains, and you email address under owners. You will get a 'Site key' and 'Secret key'. Those go inside the Web.base.config under 'recaptchaPublicKey' and 'recaptchaPrivateKey'.

You should now be able to build and run Voat on your machine.

**Comment by Romoku** [comment]
I am currently working on automating the database setup portion I outlined above.

**Comment by TNTGav** [comment]
Thanks for that. I already have VS 2013 installed and can setup a working voat from my own fork I was more wondering about how the AppVeyor works and how you set the different configs. I think what I'm struggling with is how having AppVeyor is a benefit as my local machine builds the solution within a few seconds. I feel like I am missing something :)!

**Comment by Romoku** [comment]
AppVeyor increases visibility into the state of the Voat project, build pull requests, and automatically deploy when the build and tests pass. We can have a development website always running the latest code and websites to test pull requests.

This adds value by reducing the time spent on manual tasks like cloning pull requests, building them, running the test suite. It also allows us to have an up-to-date public development environment for testing.

**Comment by TNTGav** [comment]
I see, that makes more sense. Does that have to run directly on the actual voat project or can it run on a fork as I assume yours is doing now?

One of the problems I've been having getting started to use github is I struggle to keep my local copy up to date when there are additional pull requests. I've just been reforking the project to do my next pull request. I can sync up to date but that gave me odd errors when I submitted pull requests that I was one commit ahead.

I think I need to do some reading!

**Comment by Romoku** [comment]
AppVeyor runs on the repository it is linked to. You can setup your own AppVeyor account and link it to your fork to build. The overall goal is to have a workflow:

* Make changes
* Run build.cmd
* build and tests pass
* commit and push to own fork
* Create pull request
* Pull request builder runs build and tests
* Code is merged when there are no merge conflicts, pull request builder succeeds, and code is reviewed
* Code is automatically deployed on the development site

Eventually I hope to have releases that will automatically go to prod:

* Create a branch `release/v$`
* Build, unit tests, and acceptance tests pass on release branch
* Code is deployed to a staging environment
* Staging website is deemed stable
* Release branch is merged to master
* master deploys to live website

In order to get there we need:

* Comprehensive suite of tests
* Automatic database migrations
* Infrastructure

I am working on the first two.

**Comment by Romoku** [comment]
@TNTGav To sync my forks I usually have a remote called `upstream` that points to the parent repository. Then I can git rebase on `upstream` after I make my changes.

**Comment by TNTGav** [comment]
Thanks for your help Romoku, it's been eye opening and much appreciated!

**Comment by Romoku** [comment]
No problem. Feel free to ask additional questions when you need help.

**Comment by Romoku** [comment]
Database setup is now working using the `build.cmd MigrateDatabase`. Should investigate real migrations in #2.
